- hosts: 127.0.0.1
  roles:
    - { role: rvm_io.rvm1-ruby, tags: ruby, sudo: true }
  remote_user: pi
  connection: local
  tasks:

    - name: ensure mpd is stopped
      service: name=mpd state=stopped
      become: yes
    
    - name: ensure mopidy is running
      become_user: pi
      become: yes
      shell: /usr/local/bin/mopidy &
      
    - name: ensure ngrok is running
      become: yes
      become_user: pi
      shell: rvm gemset use global && ruby /home/pi/reboot.rb && touch blah.txt

    - name: ensure ngrok is running
      become: yes
      become_user: pi
      shell: /usr/local/bin/ngrok start music ssh
