- hosts: 127.0.0.1
  remote_user: pi
  connection: local
  roles:
    - { role: rvm_io.rvm1-ruby, tags: ruby, sudo: True }
  tasks:

    - name: ensure mpd is stopped
      service: name=mpd state=stopped
      become: yes
    
    - name: ensure mopidy is running
      become_user: pi
      become: yes
      shell: /usr/local/bin/mopidy &
      
    - name: ensure ngrok is running
      become: yes
      become_user: pi
      shell: . $(rvm 2.2.1 do rvm env --path) && rvm gemset use global && ruby /home/pi/reboot.rb &

    - name: ensure ngrok is running
      become: yes
      become_user: pi
      shell: /usr/local/bin/ngrok start music ssh
