- hosts: 127.0.0.1
  remote_user: pi
  connection: local
  environment:
    PATH: /home/pi/.rvm/gems/ruby-2.2.1/bin:/home/pi/.rvm/gems/ruby-2.2.1@global/bin:/home/pi/.rvm/rubies/ruby-2.2.1/bin:/home/pi/.rvm/gems/ruby-2.2.1@global/bin:/home/pi/.rvm/rubies/ruby-2.2.1/bin:/home/pi/.rvm/bin:/home/pi/go/bin:/home/pi/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/usr/lib/go/bin:/home/pi/go/bin:/usr/local/lib:/usr/local/lib/
    GEM_PATH: /home/pi/.rvm/gems/ruby-2.2.1:/home/pi/.rvm/gems/ruby-2.2.1@global
    GEM_HOME: /home/pi/.rvm/gems/ruby-2.2.1
  tasks:

    - name: ensure mpd is stopped
      service: name=mpd state=stopped
      become: yes
    
    - name: ensure mopidy is running
      become_user: pi
      become: yes
      shell: /usr/local/bin/mopidy &
    
    - name: ensure ngrok is running
      become: yes
      become_user: pi
      shell: /usr/local/bin/ngrok start music ssh &
      
    - name: ensure big red button is running
      become: yes
      become_user: pi
      shell: . $(rvm 2.2.1 do rvm env --path) && rvm gemset use global && ruby /home/pi/reboot.rb

    - name: run voicecommand
      become: yes
      become_user: pi
      shell: /usr/bin/voicecommand
